//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class catalogobitacora
    {
        public int CatalogoBitacoraId { get; set; }
        public int ModelosId { get; set; }
        public int TallaId { get; set; }
        public int TipoId { get; set; }
        public int ColorId { get; set; }
        public int Docenas { get; set; }
        public int EstatusId { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public int UsuarioId { get; set; }
    
        public virtual colores colores { get; set; }
        public virtual estatus estatus { get; set; }
        public virtual modelos modelos { get; set; }
        public virtual talla talla { get; set; }
        public virtual tipo tipo { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
