//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSam.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AppSamEntities : DbContext
    {
        public AppSamEntities()
            : base("name=AppSamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<catalogo> catalogo { get; set; }
        public virtual DbSet<catalogobitacora> catalogobitacora { get; set; }
        public virtual DbSet<colores> colores { get; set; }
        public virtual DbSet<estatus> estatus { get; set; }
        public virtual DbSet<MenuTitulo> MenuTitulo { get; set; }
        public virtual DbSet<modelos> modelos { get; set; }
        public virtual DbSet<Pantallas> Pantallas { get; set; }
        public virtual DbSet<talla> talla { get; set; }
        public virtual DbSet<tipo> tipo { get; set; }
        public virtual DbSet<UsuarioAcceso> UsuarioAcceso { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
        public virtual DbSet<UsuariosPantallas> UsuariosPantallas { get; set; }
        public virtual DbSet<UsuarioToken> UsuarioToken { get; set; }
    }
}
