//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pantallas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pantallas()
        {
            this.UsuariosPantallas = new HashSet<UsuariosPantallas>();
        }
    
        public int PantallaId { get; set; }
        public int MenuTituloId { get; set; }
        public string Descripcion { get; set; }
        public string DireccionPantalla { get; set; }
        public string Icono { get; set; }
    
        public virtual MenuTitulo MenuTitulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuariosPantallas> UsuariosPantallas { get; set; }
    }
}
