//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class talla
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public talla()
        {
            this.catalogo = new HashSet<catalogo>();
            this.catalogobitacora = new HashSet<catalogobitacora>();
        }
    
        public int TallaId { get; set; }
        public string Descripcion { get; set; }
        public int EstatusId { get; set; }
        public int usuarioId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalogo> catalogo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalogobitacora> catalogobitacora { get; set; }
        public virtual estatus estatus { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
