//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioToken
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsuarioToken()
        {
            this.UsuarioAcceso = new HashSet<UsuarioAcceso>();
        }
    
        public int UsuarioTokenId { get; set; }
        public string IP { get; set; }
        public int UsuarioId { get; set; }
        public string Token { get; set; }
        public int EstatusId { get; set; }
    
        public virtual estatus estatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioAcceso> UsuarioAcceso { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
